package earth.praesideo.enums;

public enum ImpactmFinalizeRecordType {
    REF_OP_BOUNDARY_SCOPE1_STATIONARY_COMBUSTION,
    REF_OP_BOUNDARY_SCOPE1_MOBILE_COMBUSTION,
    REF_OP_BOUNDARY_SCOPE1_REFRIGERANTS,
    REF_OP_BOUNDARY_SCOPE2_PURCHASED_ELECTRICITY,
    REF_OP_BOUNDARY_SCOPE3_EMPLOYEE_COMMUTE,
    REF_OP_BOUNDARY_SCOPE3_BUSINESS_TRAVEL,
    SCOPE1,
    SCOPE2,
    SCOPE3;
}
