CREATE TABLE IF NOT EXISTS static.t_impact_temperature_alignment
(
    record_type                                  integer not null,
    year                                         integer not null,
    scope1_actual_long_term                      double precision,
    scope1_actual_short_term                     double precision,
    scope1_1_5_long_term                         double precision,
    scope1_1_5_short_term                        double precision,
    scope1_2_long_term                           double precision,
    scope1_2_short_term                          double precision,
    probability_1_5_degree                       double precision,
    probability_1_5_degree_type                  varchar(255),
    probability_1_5_degree_scope_1               double precision,
    probability_1_5_degree_scope_1_type          varchar(255),
    probability_1_5_degree_scope_2               double precision,
    probability_1_5_degree_scope_2_type          varchar(255),
    probability_1_5_degree_scope_3               double precision,
    probability_1_5_degree_scope_3_type          varchar(255),
    probability_2_degree                         double precision,
    probability_2_degree_type                    varchar(255),
    probablity_2_degree_scope_1                  double precision,
    probablity_2_degree_scope_1_type             varchar(255),
    probablity_2_degree_scope_2                  double precision,
    probablity_2_degree_scope_2_type             varchar(255),
    probablity_2_degree_scope_3                  double precision,
    probablity_2_degree_scope_3_type             varchar(255),
    scope2_actual_long_term                      double precision,
    scope2_actual_short_term                     double precision,
    scope2_1_5_long_term                         double precision,
    scope2_1_5_short_term                        double precision,
    scope2_2_long_term                           double precision,
    scope2_2_short_term                          double precision,
    temperature_alignment_score_overall          double precision,
    temperature_alignment_score_overall_type     varchar(255),
    temperature_score_overall_scope_1            double precision,
    temperature_score_overall_scope_1_type       varchar(255),
    temperature_score_overall_scope_2            double precision,
    temperature_score_overall_scope_2_type       varchar(255),
    temperature_score_overall_scope_3            double precision,
    temperature_score_overall_scope_3_type       varchar(255),
    scope3_actual_long_term                      double precision,
    scope3_actual_short_term                     double precision,
    scope3_1_5_long_term                         double precision,
    scope3_1_5_short_term                        double precision,
    scope3_2_long_term                           double precision,
    scope3_2_short_term                          double precision,
    transition_pathway_overall_actual_long_term  double precision,
    transition_pathway_overall_actual_short_term double precision,
    transition_pathway_overall_1_5_long_term     double precision,
    transition_pathway_overall_1_5_short_term    double precision,
    transition_pathway_overall_2_long_term       double precision,
    transition_pathway_overall_2_short_term      double precision,
    company_id                                   integer not null
        constraint fk_t_impact_temperature_alignment_t_companies
            references t_companies(company_id),
    constraint t_impact_temperature_alignment_pkey
        primary key (company_id, record_type, year)
);
