package earth.praesideo.database.entities.tech;

public enum AppLogType {
    EMAIL_REGISTRATION,
    RESTORE_PWD,
    SUPPLIER_INVITATION,
    TEMPERATURE_ALIGNMENT,
    FILE_UPLOAD,
    DOWNLOAD_FX_RATES,
    GENERATE_IMPACT_TEMPERATURE_ALIGNMENT,
    LOGIN
}
